# Generated by Django 6.0.2 on 2026-03-01 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event_type',
            field=models.CharField(max_length=1000),
        ),
    ]
