# Generated by Django 6.0.2 on 2026-03-01 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_notification_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event_type',
        ),
    ]
