# Generated by Django 6.0.2 on 2026-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_remove_notification_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(default='EMAIL', max_length=1000),
        ),
    ]
