# Generated by Django 6.0.2 on 2026-03-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_notification_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
