# Generated by Django 6.0.2 on 2026-03-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='44142956', max_length=10, unique=True),
        ),
    ]
