# Generated by Django 6.0.2 on 2026-02-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='amount',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='44568170', max_length=10, unique=True),
        ),
    ]
